import { Dimensions, StyleSheet } from 'react-native';
import { palette, spacing, typography } from '../../tokens';

const { height: SCREEN_HEIGHT } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: palette.bg },
  content: { paddingHorizontal: spacing.xl, paddingBottom: spacing.xxxl * 2 },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.xxxl },
  pageTitle: { color: palette.ink, fontSize: 42, fontFamily: typography.primaryBold, lineHeight: 48, includeFontPadding: false },
  bellButton: { width: 44, height: 44, borderRadius: 22, backgroundColor: palette.white, borderWidth: 1, borderColor: palette.border, alignItems: 'center', justifyContent: 'center', elevation: 2, shadowColor: palette.ink, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.04, shadowRadius: 8 },
  notifDot: { position: 'absolute', top: 9, right: 9, width: 8, height: 8, borderRadius: 4, backgroundColor: palette.primary, borderWidth: 1.5, borderColor: palette.white },
  bentoContainer: { gap: spacing.lg },
  bentoRow: { flexDirection: 'row', gap: spacing.lg },
  cardFull: { backgroundColor: palette.white, borderRadius: 24, padding: spacing.xl, borderWidth: 1, borderColor: palette.border, height: 180, justifyContent: 'space-between', elevation: 2, shadowColor: palette.ink, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.04, shadowRadius: 12 },
  alertCard: { backgroundColor: palette.secondarySoft, borderColor: palette.secondary, borderWidth: 1 },
  successCard: { backgroundColor: palette.white, borderColor: palette.border, borderWidth: 1 },
  cardHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  cardBody: { gap: 4 },
  subtleTag: { fontFamily: typography.primaryBold, fontSize: 10, color: palette.primary, letterSpacing: 1 },
  alertTag: { fontFamily: typography.primaryBold, fontSize: 10, color: palette.ink, letterSpacing: 1 },
  successTag: { fontFamily: typography.primaryBold, fontSize: 10, color: palette.muted, letterSpacing: 1 },
  squareIconLight: { position: 'absolute', top: spacing.xl, right: spacing.xl, opacity: 0.7, transform: [{ rotate: '-45deg' }] },
  squareIconDark: { position: 'absolute', top: spacing.xl, right: spacing.xl, opacity: 0.4, transform: [{ rotate: '-45deg' }] },
  bentoSquare: { flex: 1, aspectRatio: 1, borderRadius: 24, padding: spacing.xl, justifyContent: 'flex-end', elevation: 2, shadowColor: palette.ink, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.04, shadowRadius: 12 },
  bgPrimary: { backgroundColor: palette.primary },
  bgSurface: { backgroundColor: palette.white, borderWidth: 1, borderColor: palette.border },
  label: { color: palette.muted, fontSize: 13, fontFamily: typography.primaryRegular, textTransform: 'uppercase', letterSpacing: 1 },
  alertLabel: { color: palette.ink, fontSize: 13, fontFamily: typography.primaryBold, textTransform: 'uppercase', letterSpacing: 1 },
  successLabel: { color: palette.muted, fontSize: 13, fontFamily: typography.primaryBold, textTransform: 'uppercase', letterSpacing: 1 },
  cardHeader: { color: palette.ink, fontSize: 24, fontFamily: typography.primaryBold },
  alertHeader: { color: palette.ink, fontSize: 24, fontFamily: typography.primaryBold },
  successHeader: { color: palette.ink, fontSize: 24, fontFamily: typography.primaryBold },
  cardSub: { color: palette.muted, fontSize: 15, fontFamily: typography.primaryRegular },
  alertSub: { color: palette.ink, fontSize: 15, fontFamily: typography.primaryRegular },
  successSub: { color: palette.muted, fontSize: 15, fontFamily: typography.primaryRegular },
  squareTextLight: { color: palette.white, fontSize: 18, fontFamily: typography.primaryBold },
  squareTextDark: { color: palette.ink, fontSize: 18, fontFamily: typography.primaryBold },

  badgeBase: { alignSelf: 'flex-start', paddingHorizontal: spacing.lg, paddingVertical: spacing.sm, borderRadius: 100, borderWidth: 1 },
  badgeActive: { backgroundColor: palette.primary, borderColor: palette.primary },
  badgeNeutral: { backgroundColor: palette.bg, borderColor: palette.border },
  badgeTextActive: { color: palette.white, fontFamily: typography.primaryBold, fontSize: 11, textTransform: 'uppercase', letterSpacing: 1 },
  badgeTextNeutral: { color: palette.ink, fontFamily: typography.primaryBold, fontSize: 11, textTransform: 'uppercase', letterSpacing: 1 },

  notifModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.xl,
  },
  notifCard: {
    width: '100%',
    backgroundColor: palette.white,
    borderRadius: 28,
    padding: spacing.xxl,
    elevation: 24,
    shadowColor: palette.ink,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
  },
  notifHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.xl,
  },
  notifTitle: {
    color: palette.ink,
    fontSize: 18,
    fontFamily: typography.primaryBold,
  },
  notifBody: {
    alignItems: 'center',
  },
  notifIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: palette.bg,
    borderWidth: 1,
    borderColor: palette.border,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.lg,
  },
  notifItemTitle: {
    color: palette.ink,
    fontSize: 20,
    fontFamily: typography.primaryBold,
    textAlign: 'center',
    marginBottom: spacing.xs,
  },
  notifItemSub: {
    color: palette.muted,
    fontSize: 14,
    fontFamily: typography.primaryRegular,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: spacing.xxl,
  },
  notifActionBtn: {
    width: '100%',
    backgroundColor: palette.primary,
    paddingVertical: 16,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notifActionBtnDisabled: {
    opacity: 0.7,
  },
  notifActionText: {
    color: palette.white,
    fontFamily: typography.primaryBold,
    fontSize: 14,
    letterSpacing: 0.5,
  },
  notifStatusPill: {
    width: '100%',
    backgroundColor: palette.bg,
    borderWidth: 1,
    borderColor: palette.border,
    paddingVertical: 16,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notifStatusText: {
    color: palette.ink,
    fontFamily: typography.primaryBold,
    fontSize: 14,
    letterSpacing: 0.5,
  },

  rcModalBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.5)' },
  rcBottomSheet: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: SCREEN_HEIGHT,
    backgroundColor: palette.white,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingHorizontal: spacing.xxl,
    elevation: 24,
    shadowColor: palette.ink,
    shadowOffset: { width: 0, height: -12 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
  },
  dragHandleArea: {
    width: '100%',
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.sm,
  },
  dragIndicator: {
    width: 48,
    height: 5,
    backgroundColor: palette.border,
    borderRadius: 3,
  },
  rcModalHeaderIconWrap: { alignSelf: 'center', width: 64, height: 64, borderRadius: 32, backgroundColor: palette.secondarySoft, borderWidth: 1, borderColor: palette.secondary, alignItems: 'center', justifyContent: 'center', marginBottom: spacing.lg },
  rcModalTitle: { alignSelf: 'center', color: palette.ink, fontSize: 22, fontFamily: typography.primaryBold, textAlign: 'center', marginBottom: 4 },
  rcModalSub: { alignSelf: 'center', color: palette.muted, fontSize: 14, fontFamily: typography.primaryRegular, textAlign: 'center', marginBottom: spacing.xl },
  rcListLabel: { color: palette.ink, fontSize: 12, fontFamily: typography.primaryBold, letterSpacing: 0.5, marginBottom: spacing.sm },

  rcListWrapper: {
    flex: 1,
    width: '100%',
    marginBottom: spacing.lg,
  },
  rcList: {
    width: '100%',
  },
  rcListContent: {
    paddingBottom: spacing.lg,
  },

  rcClassItem: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: palette.white, padding: spacing.lg, borderRadius: 16, borderWidth: 1, borderColor: palette.border, marginBottom: spacing.sm },
  rcClassItemSelected: { borderColor: palette.primary, backgroundColor: '#FFF5F5' },
  rcClassInfo: { flexShrink: 1, paddingRight: spacing.sm },
  rcClassName: { color: palette.ink, fontSize: 15, fontFamily: typography.primaryBold, marginBottom: 2 },
  rcClassSubName: { color: palette.muted, fontSize: 13, fontFamily: typography.primaryMedium },

  liveBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FEE2E2', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 100 },
  liveDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#DC2626', marginRight: 6 },
  liveText: { color: '#DC2626', fontSize: 11, fontFamily: typography.primaryBold, letterSpacing: 0.5 },
  emptySheet: { paddingVertical: spacing.xxxl, alignItems: 'center' },
  emptySheetText: { color: palette.muted, fontFamily: typography.primaryMedium, fontSize: 15 },

  rcModalFooter: { flexDirection: 'row', width: '100%', justifyContent: 'space-between', alignItems: 'center' },
  rcCancelBtn: { paddingVertical: spacing.sm, paddingHorizontal: spacing.md },
  rcCancelText: { color: palette.muted, fontSize: 14, fontFamily: typography.primaryBold, letterSpacing: 0.5 },
  rcContinueBtn: { backgroundColor: palette.primary, paddingVertical: 14, paddingHorizontal: spacing.xxl, borderRadius: 100, alignItems: 'center', justifyContent: 'center' },
  rcContinueBtnDisabled: { backgroundColor: palette.border },
  rcContinueText: { color: palette.white, fontSize: 14, fontFamily: typography.primaryBold, letterSpacing: 0.5 },
});
